### ISSUE TITLE
How does this compare to similar projects?

### ISSUE THREAD

**Issue by ylluminarious** [bakpakin/fnl#2]
There are [a](https://github.com/larme/hua) [lot](https://github.com/NalaGinrut/guile-lua-rebirth) [of](https://github.com/meric/l2l) [projects](https://github.com/leafo/moonlisp) that seem similar in scope to this one. What makes this one stand out (aside from having the most recent contributions)? Just curious.

EDIT:

[Here](https://github.com/SquidDev/urn) is yet another such project, although it also has recent contributions.

**Comment by bakpakin** [comment]
The biggest difference between this and most Lua lisps I found is that most Lisp->Lua compilers are tied to the idea of singularly linked lists. Singly linked lists in general are usually not as performant as arrays, and Lua provides a perfectly fine dynamic array implementation. Languages like Clojure prove you can code in lisp perfectly well with a different underlying data structure than the singly linked list.

Fnl uses Lua tables as arrays to represent Lists. This means the traditional consing and such is not very useful. As a side effect, however, real world code is faster and should work better with existing Lua libraries.

Fnl is also not trying to be scheme or Common Lisp. It is it’s own thing, and features correspond directly to Lua. You want continuations? Use Lua coroutines, or write some functions or macros that make them look like continuations.

There may be other projects with similar characteristics. Current problems with fnl would be the lack of source mapping and documentation. However, a repl and a single file implementation means you can read the source yourself.

**Comment by ylluminarious** [comment]
@bakpakin Awesome, thanks for the info! I'll leave this open for a little while longer in case anyone else wants to chime in. Or I can close it now if you'd like (or you can).

**Comment by technomancy** [comment]
When you say in the readme "a standard library needs to be made" what did you have in mind? To me, one of the strengths of this lisp is that like Lua, it allows you to bring your own standard library. So I will use it with https://github.com/rxi/lume but others might prefer https://github.com/stevedonovan/Penlight or https://github.com/lua-stdlib/lua-stdlib

The only thing I can think of that might be worth including optionally which Lume wouldn't provide would be first-class function versions of `+`, `*`, `>`, etc; were you thinking of that or something bigger?

**Comment by bakpakin** [comment]
I was really thinking about some combinators. Reduce, map, and the like that function over standard Lua iterators.

While these could be special forms, at some point it is preferable to add functions rather than special forms.
