### ISSUE TITLE
Table iteration form

### ISSUE THREAD

**Issue by technomancy** [bakpakin/fnl#9]
We have the `*for` form, but it only works with "numeric for", not with `pairs` and `ipairs`. Should we introduce a new form for table iteration; maybe `each`? Is the star in the name of `*for` intended to indicate an internal implementation detail, or is there some other meaning?

I noticed that `*for` takes its arguments in an unusual way: `(*for i [begin end] body)` instead of keeping `i` inside the vector like most lisps do. If it were up to me I would implement table iteration as `(each [k v (pairs tbl)] (print k v))` where the last element in the vector is the iterator call, and you can bind as many loop locals as the iterator will return. But that's different from the existing `*for` so I thought I'd ask before implementing.

**Comment by bakpakin** [comment]
All of the forms that begin a * are forms that can definitely be subject to change. The leading * was to indicate that in the future, I would like to avoid relying on these too much in written code. The original idea for their existence was to expose them for macros.

Feel free to change them as you want, but i'd like to make it possible to write pretty much all constructs available in standard Lua.

I agree that the *for syntax is a bit weird, and could definitely be expanded to handle iterators.
